spring: 
   profiles: 
      active: prod
      
#配置访问路径
server: 
   servlet: 
      context-path: /boot
      

---
server: 
   port: 8010

spring: 
   profiles: dev
   
---
server:
   port: 8011
   
spring:
   profiles: prod 
   config: 
      location: 

---
person: 
    name: lizhe
    age: 28
    boss: false
    birth: 1993/01/13
    maps: {k1:v1,k2:v2}
    list:
     - darry
     - suwent
     - aline
    dog:
      name: wangcai
      age: 3